# Generated by Django 3.2.7 on 2021-09-28 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productder',
            new_name='producter',
        ),
    ]
