# Generated by Django 3.2.7 on 2021-09-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_productder_product_producter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品管理', 'verbose_name_plural': '产品管理'},
        ),
    ]
