# Generated by Django 3.2.7 on 2021-09-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apitest',
            options={'verbose_name': '流程场景接口', 'verbose_name_plural': '流程场景接口'},
        ),
        migrations.RemoveField(
            model_name='apitest',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='apitest',
            name='apitestdesc',
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apimethod',
            field=models.CharField(max_length=200, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='apitester',
            field=models.CharField(max_length=16, verbose_name='执行人'),
        ),
    ]
